# -*- coding: utf-8 -*-
"""PRML PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzgwruq-AMpPQIWN-u8PxnbgH6-rFliP

# **DOCUMENT CLUSTERING AND TOPIC MODELLING**

## **Data Loading and dividing into coulmns**
"""

import pandas as pd

data = pd.read_csv('abcnews-date-text.csv')
publish_date = data.iloc[:,0]
headlines = data.iloc[:,1]


print(data.shape)
print()
print(data.iloc[0,0])
print()
print(publish_date[2])
print()
print(headlines.isnull().sum())
print(headlines.duplicated().sum())
unique_lines = headlines.drop_duplicates()
print(unique_lines.duplicated().sum())

"""## **Text Preprocessing and Text Representation**"""

import re


def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

cleaned_headlines = unique_lines.apply(clean_text)
print(cleaned_headlines.head())

import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text_series):
    processed = []

    for text in text_series:
        words = text.split()

        words = [
            lemmatizer.lemmatize(word)
            for word in words
            if word.isalpha() and word not in stop_words
        ]

        processed.append(",".join(words))

    return processed


final_list = preprocess(cleaned_headlines[:1244184])
final_headlines = pd.Series(final_list)

print(final_headlines.head())

"""## **Clusters**

Text Representation
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
tfidf_data = tfidf_vectorizer.fit_transform(final_headlines[:1244184])

print(tfidf_data.shape)

"""Kmeans Clustering"""

import sklearn
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

sum_of_squared_distances = []
K = range(21,34)

for k in K:
    km = KMeans(n_clusters=k, max_iter=200, n_init=10, random_state=42)
    km = km.fit(tfidf_data)
    sum_of_squared_distances.append(km.inertia_)



plt.figure(figsize=(10, 5))
plt.plot(K, sum_of_squared_distances, 'bx-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia (Sum of squared distances)')
plt.title('Elbow Method For Optimal k')
plt.show()

"""Validation"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


scores = []
K = range(2 , 70 )

for k in K:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(tfidf_data[:5000])
    score = silhouette_score(tfidf_data[:5000], labels)
    scores.append(score)
    print(f"k={k}, score={score}")
print(score)

"""Visualizing"""

from sklearn.manifold import TSNE
import seaborn as sns
import pandas as pd


sample_size = 5000
final_km = KMeans(n_clusters=19, random_state=42).fit(tfidf_data[:sample_size])
labels = final_km.labels_


tsne = TSNE(n_components=2, perplexity=30, random_state=42, init='pca', learning_rate='auto')
tsne_results = tsne.fit_transform(tfidf_data[:sample_size].toarray())


df_tsne = pd.DataFrame(tsne_results, columns=['X', 'Y'])
df_tsne['Cluster'] = labels
plt.figure(figsize=(12, 8))
sns.scatterplot(data=df_tsne, x='X', y='Y', hue='Cluster', palette='deep', legend='full', alpha=0.6)
plt.title('t-SNE Visualization of News Headline Clusters')
plt.show()

"""## **Topic Modelling**"""

from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
count_data = count_vectorizer.fit_transform(final_headlines[:1244184])

print(f"Count Matrix Shape: {count_data.shape}")

"""LDA"""

from sklearn.decomposition import LatentDirichletAllocation

best_k = 10

lda_model = LatentDirichletAllocation(
    n_components=best_k,
    max_iter=10,
    learning_method='online',
    random_state=42
)

lda_output = lda_model.fit_transform(count_data)

"""Topic words per topic"""

pip install gensim

feature_names = count_vectorizer.get_feature_names_out()

def get_topics(model, feature_names, n_top_words=10):
    topics = []
    for topic_idx, topic in enumerate(model.components_):
        top_words = [feature_names[i] for i in topic.argsort()[-n_top_words:]]
        topics.append(top_words)
        print(f"Topic {topic_idx}: {top_words}")
    return topics

topics = get_topics(lda_model, feature_names)

"""Visualisation"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

for i, topic in enumerate(lda_model.components_):
    word_freq = {feature_names[j]: topic[j] for j in topic.argsort()[-10:]}

    wc = WordCloud(width=400, height=400, background_color='white')
    wc.generate_from_frequencies(word_freq)
    plt.figure(figsize=(1, 5))
    plt.imshow(wc)
    plt.title(f"Topic {i}")
    plt.axis("off")
    plt.show()

import numpy as np

dominant_topics = np.argmax(lda_output, axis=1)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=dominant_topics, palette='tab10')
plt.title("Topic Distribution Across Headlines")
plt.xlabel("Topic Number")
plt.ylabel("Number of Headlines")
plt.xticks(range(10), [f'Topic {i}' for i in range(10)], rotation=45)
plt.tight_layout()
plt.show()
